### ISSUE TITLE
decode is not a function

### ISSUE THREAD

**Issue by xnng** [VyrekXD/MAG#11]
where is your decode funcion ? I can't run it.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/38936252/177003135-0eb04dd3-1fa1-40d3-bf37-6916e72d7b48.png">

**Comment by VyrekXD** [comment]
Hello! If you see in the readme the function encode it's what returns the GIF, I was using imagescript functions as a base to name my functions. You should use the encode function to get the GIF

**Comment by xnng** [comment]
Thanks for your reply. I modified two parts of code in readme and it can run successfully.
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/38936252/177004719-c60f8370-f7b0-4be0-99a7-5f14d733de05.png">
